branch-defaults:
  default:
    environment: storeAPI-env
    group_suffix: null
environment-defaults:
  storeAPI-env:
    branch: null
    repository: null
global:
  application_name: storeAPI
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
